services:
  nginx-proxy:
    image: nginx:stable-alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./ssl:/etc/nginx/ssl
      - ./wordpress:/var/www/html
      - ./cache:/etc/nginx/conf.d/cache/ 
    networks:
      - proxy_network 

networks:
  proxy_network:
    external: true
