services:
  nginx-proxy:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./ssl:/etc/nginx/ssl
      - ./wordpress:/var/www/html
      - ./cache:/etc/nginx/cache/
      - ./globals:/etc/nginx/globals/
    networks:
      - proxy_network 

  redis:
    image: redis:alpine
    container_name: redis-cache
    restart: unless-stopped
    networks:
      - proxy_network
    command: redis-server --appendonly yes

networks:
  proxy_network:
    external: true
