services:
  nginx-proxy:
    container_name: nginx-proxy
    image: openresty/openresty:1.21.4.1-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./ssl:/etc/nginx/ssl
      - ./wordpress:/var/www/html
      - ./cache:/etc/nginx/cache/
      - ./globals:/etc/nginx/globals/
      - ./globals/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
      - ./cache/fastcgi:/usr/local/openresty/nginx/fastcgi_cache
    networks:
      - proxy_network 

networks:
  proxy_network:
    external: true
